name: Insights
on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed
jobs: 
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.repository }}"
      - uses: actions/checkout@v4 
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer
      - name: Run lighthouse tests
        run: unlighthouse-ci --site ${{ env.URL }} --debug --build-static --output-path insights
