name: Insights
on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed
jobs: 
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
        with:
          fetch-depth: 0
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer wrangler
      - name: Run lighthouse tests
        run: unlighthouse-ci --site $URL --debug --build-static --output-path insights
      - name: Deploy
        run: npx wrangler pages deploy insights --project-name=$PROJECT --outdir=./insights
