name: Pagespeed Report
on:
  check_run:
    types: [completed]
jobs: 
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Get Deployment URL
        run: echo "DEPLOYMENT_URL=$(echo "${{ github.event.check_run.output.summary }}" | grep -o "href\=.*>https" | cut -c 7-43)" >> $GITHUB_ENV

  generate:
    needs: prepare
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run:  npm install -g @unlighthouse/cli puppeteer
      - name: Run lighthouse tests
        run: unlighthouse-ci --site ${{ vars.URL }} --debug --build-static --output-path pagespeed-report
      - name: Store Pagespeed Report for deploy
        uses: actions/upload-artifact@v4
        with:
          name: pagespeed-report
          path: pagespeed-report
        
  deploy: 
    needs: generate
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get Pagespeed Report
        uses: actions/download-artifact@v4
        with:
          name: pagespeed-report
      - name: Files to deploy
        run: ls
